### ISSUE TITLE
Need help on using .in files

### ISSUE THREAD

**Issue by ghost** [nomadbsd/website#17]
Hello, I would like to contribute to this repository, but the files, while the contents are mostly HTML code, the filename extension is `.in`.

Do I have to use a certain program, or can I edit it directly? Thank you.

**Comment by mrclksr** [comment]
Hi @azraeljd,

these are normal text files from which the *.html files are generated when running `make`. Everything between `CONTENT_START` and `CONTENT_END` in each *.in files is inserted at the placeholder `@CONTENT@` in a copy of the `template` file. The content of variables at the beginning of each *.in file is inserted at the matching placeholder in a copy of the `template` file.

**Comment by ghost** [comment]
But how do I make it back to `.in` so that I can contribute back to this repo?

**Comment by mrclksr** [comment]
1. Edit the .in file(s)
2. Test your changes:
    1. Create the `Makefile` if not already there: `./mkmf > Makefile`
    2.  Build the html files by running `make`, and check the result with your browser.
    3. Type `make clean` to delete the \*.html files.
3. commit and push to your forked repo
4. Send a pull request

**Comment by ghost** [comment]
Alright, thank you for the help.
