### ISSUE TITLE
PDF Handbook Needs an Update

### ISSUE THREAD

**Issue by mrclksr** [nomadbsd/website#19]
The PDF handbook needs an update to match the content of https://github.com/nomadbsd/handbook/blob/master/handbook.md

**Comment by mmertgunduz** [comment]
Great! 

Thanks for assigning me, will work on it today! :-)

**Comment by mrclksr** [comment]
Thank you :-)

**Comment by mmertgunduz** [comment]
Hey @mrclksr 

I have finished the "Handbook PDF"  and pushed into the repo.

<hr>

Also fixed these bugs and typos: 

> ### 1 - Index page first typo
NomadBSD developermailing list changed to NomadBSD developer mailing list

<br>

> ### 2 - Index page second typo
achitecture changed to architecture

<br>

> ### 3 - Handbook page openbox menu hyperlink 
https://freshports/x11-wm/openbox changed to https://www.freshports.org/x11-wm/openbox

<hr>

Also I have published a new post about NomadBSD 131R-20221130 on LinkedIn :-)

- LinkedIn Post: https://www.linkedin.com/feed/update/urn:li:share:7005305974521511937/

Will work on the other Turkish translations soon!

**Comment by mrclksr** [comment]
Good work. Thank you :-)

**Comment by mmertgunduz** [comment]
You're welcome! :-)
