### ISSUE TITLE
IRC channel

### ISSUE THREAD

**Issue by pynixis** [nomadbsd/website#3]
Having issues connecting to the IRC channel. The IRC channel information may be outdated.

**Comment by bsdlme** [comment]
Thanks for reporting this! I just changed the information to reflect that we moved to libera.chat. Unfortunately it's not really crowded there.

@mrclksr: Can you please upload the new version to the website? I don't have access to it at the moment.

**Comment by mrclksr** [comment]
Uploaded. Thanks :)
