### ISSUE TITLE
Changing The HTML4 to HTML5.

### ISSUE THREAD

**Issue by mmertgunduz** [nomadbsd/website#8]
Hello Marcel!

I'm trying to change the HTLM4 structure to HTML5, but It looks like it is impossible to do it with the .in files. Can we stop using the .in files and go for default HTML?

Let me know please :-)

Best regards,

**Comment by mrclksr** [comment]
Hi there, Mehmet!

Look at `template.in`. It is the basis for all pages, and it defines the HTML version. For each .in file, the build script replaces the placeholder `@CONTENT@` from `template.in` with the content of the .in file. Take `index.in`, for instance: The build script takes the template file, inserts the content from `index.in` at `@CONTENT@`, and writes the result to `index.html`.

But you are free to create a different build system. The most important part is that we can automatically regenerate the `mirror.html` and the `download.html` page when we add/remove a mirror to/from the `mirrors` file, or when we add a new release. Creating all the download links by hand would be a real PITA :-)

Feel free to ask if there is anything unclear.

**Comment by mmertgunduz** [comment]
Thanks for the fast reply! 

I got the system right now, I can build the system now! 

I will build something looks really good and responsive for mobile phones. Excited to develop :-)

**Comment by mrclksr** [comment]
Great! I'm looking forward to it :-)
